inoremap jj <ESC>
nnoremap B ^
nnoremap E $

set clipboard=unnamed
set clipboard=unnamedplus
hi folded ctermbg=darkgrey

let mapleader = "\<Space>"
nnoremap <Leader>w :w<CR>
nnoremap <Leader>x :x<CR>
nnoremap <Leader>q :q<CR>

syntax on
let python_highlight_all = 1

set encoding=utf-8
